In [3]:
import numpy as np

# Numpy is main used or mathematical manipulations. 

In [2]:
np.__version__

'1.19.1'

In [4]:
!pip install numpy

Note: you may need to restart the kernel to use updated packages.


#### Create Numpy array

In [9]:
a = np.array([])

In [11]:
print(a, type(a))

[] <class 'numpy.ndarray'>


In [4]:
a = np.array([1])
print(a, type(a))

[1] <class 'numpy.ndarray'>


In [7]:
b = np.array([1, 2, 3, 4, 5, 6, 7, 8,])
print(b, type(b))

[1 2 3 4 5 6 7 8] <class 'numpy.ndarray'>


In [8]:
b.shape, b.ndim, b.size

((8,), 1, 8)

In [9]:
type(b.shape), type(b.ndim), type(b.size)

(tuple, int, int)

In [14]:
b = [1, 'Pramod', [2, 3], {'Hi': 'Pramod'}]
print(b, 'has', len(b), 'elements')

for e in b:
    print(e)

[1, 'Pramod', [2, 3], {'Hi': 'Pramod'}] has 4 elements
1
Pramod
[2, 3]
{'Hi': 'Pramod'}


In [16]:
a = np.array([1, 'Pramod', [2, 3], {'Hi': 'Pramod'}])

C:\Users\admin\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  """Entry point for launching an IPython kernel.


In [20]:
a = np.array(['P', 'r', 4, 'amod'])
print(a, type(a))

['P' 'r' '4' 'amod'] <class 'numpy.ndarray'>


#### 2D array

In [21]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(a, type(a))

[[1 2 3]
 [4 5 6]
 [7 8 9]] <class 'numpy.ndarray'>


In [30]:
a.shape, a.ndim, a.size

((3, 3), 2, 9)

In [22]:
a[0]

array([1, 2, 3])

#### indexing 2D numpy array

In [27]:
a[0][0], a[0][2], a[1][1], a[-1][1]

(1, 3, 5, 8)

In [31]:
a = np.array([[1, 2, 3], [4, 5, 6],])
a.shape, a.ndim, a.size

((2, 3), 2, 6)

In [32]:
a = np.array([[[1, 2, 3], [5, 6, 7], [1, 4, 6]], [[0, 4, 1], [7, 3, 4], [6, 9, 3]],])
a.shape, a.ndim, a.size

((2, 3, 3), 3, 18)

In [37]:
a[0][2][1], a[-1][-1][-3]

(4, 6)

In [45]:
b = [[[1, 2, 3], [5, 6, 7], [1, 4, 6]], [[0, 4, 1], [7, 3, 4], [6, 9, 3]],]
b[0][2][1]

4

In [46]:
a[1, 1, 1]

3

In [50]:
a = np.zeros((4, 3, 2))
print(a, type(a))

[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]] <class 'numpy.ndarray'>


In [55]:
a = 5*np.ones((4, 3, 2))
print(a, type(a))

[[[5. 5.]
  [5. 5.]
  [5. 5.]]

 [[5. 5.]
  [5. 5.]
  [5. 5.]]

 [[5. 5.]
  [5. 5.]
  [5. 5.]]

 [[5. 5.]
  [5. 5.]
  [5. 5.]]] <class 'numpy.ndarray'>


In [54]:
a = np.empty(4)
print(a, type(a))

[0. 0. 0. 0.] <class 'numpy.ndarray'>


In [56]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [58]:
np.arange(2, 5)

array([2, 3, 4])

In [59]:
np.arange(2, 5, 2)

array([2, 4])

In [70]:
np.arange(2, 5, 0.5)

array([2. , 2.5, 3. , 3.5, 4. , 4.5])

In [71]:
range(2, 5, 0.5)

TypeError: 'float' object cannot be interpreted as an integer

#### Generate linearly spaced number sequence (constat step).

SYNTAX:
    np.linspace(start, stop, no. of elements)

    NOTE: Stop is also included in the range.

In [62]:
a = np.linspace(2, 6)
print(a, a.shape, a.ndim, a.size)

[2.         2.08163265 2.16326531 2.24489796 2.32653061 2.40816327
 2.48979592 2.57142857 2.65306122 2.73469388 2.81632653 2.89795918
 2.97959184 3.06122449 3.14285714 3.2244898  3.30612245 3.3877551
 3.46938776 3.55102041 3.63265306 3.71428571 3.79591837 3.87755102
 3.95918367 4.04081633 4.12244898 4.20408163 4.28571429 4.36734694
 4.44897959 4.53061224 4.6122449  4.69387755 4.7755102  4.85714286
 4.93877551 5.02040816 5.10204082 5.18367347 5.26530612 5.34693878
 5.42857143 5.51020408 5.59183673 5.67346939 5.75510204 5.83673469
 5.91836735 6.        ] (50,) 1 50


In [69]:
a = np.linspace(0, 10, 11)
print(a, a.shape, a.ndim, a.size)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.] (11,) 1 11


#### concatenation

In [75]:
a = np.arange(5)
b = np.arange(5, 10)
c = np.arange(10, 15)

In [76]:
np.concatenate((a, b, c))

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

#### Transpose -> exchange rows and columns

In [84]:
d = np.array([[1, 2, 3], [4, 5, 6]])
d

array([[1, 2, 3],
       [4, 5, 6]])

In [85]:
d.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [97]:
d = np.array([[1, 2, 3], [4, 5, 6]])
e = np.array([[7, 8, 9], [10, 11, 12]])

In [98]:
d, e

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[ 7,  8,  9],
        [10, 11, 12]]))

In [99]:
np.concatenate((d, e), axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [90]:
np.concatenate((d, e), axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [91]:
np.vstack((d, e))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [92]:
np.hstack((d, e))

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

#### Sorting (always sorts in ascending order, sorting by default happens at last axis)

In [110]:
d = np.array([[3, 1, 2], [-1, -5, -6]])
d

array([[ 3,  1,  2],
       [-1, -5, -6]])

In [107]:
np.sort(d)

array([[ 1,  2,  3],
       [-6, -5, -1]])

In [111]:
np.sort(d, axis=0)

array([[-1, -5, -6],
       [ 3,  1,  2]])

In [112]:
np.sort(d, axis=1)

array([[ 1,  2,  3],
       [-6, -5, -1]])